CREATE TABLE IF NOT EXISTS categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(150) NOT NULL,

CONSTRAINT pk_categories_unique UNIQUE (name),
CONSTRAINT pk_categories_primary_key PRIMARY KEY (id)
);

CREATE TABLE IF NOT EXISTS users(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(150) NOT NULL,
    email VARCHAR(300) NOT NULL,

CONSTRAINT pk_users_id PRIMARY KEY (id),
CONSTRAINT pk_unique_email UNIQUE (email)
);

CREATE TABLE IF NOT EXISTS events(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    annotation VARCHAR(512) NOT NULL,
    category_id BIGINT NOT NULL,
    confirmed_requests INT NOT NULL,
    created_on TIMESTAMP NOT NULL,
    description VARCHAR(7000) NOT NULL,
    event_date TIMESTAMP NOT NULL,
    user_id BIGINT NOT NULL,
    lat FLOAT NOT NULL,
    lon FLOAT NOT NULL,
    paid BOOLEAN NOT NULL,
    participant_limit INT NOT NULL,
    published_on TIMESTAMP NOT NULL,
    request_moderation BOOLEAN NOT NULL,
    state VARCHAR(16) NOT NULL,
    title VARCHAR(120) NOT NULL,
    views INT NOT NULL,

CONSTRAINT pk_events_id PRIMARY KEY (id),
CONSTRAINT pk_events_category_id FOREIGN KEY (category_id) REFERENCES categories(id),
CONSTRAINT pk_events_users_id FOREIGN KEY (user_id) REFERENCES users(id)
);