CREATE TABLE IF NOT EXISTS categories(
    id BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    name VARCHAR(150) NOT NULL,

    CONSTRAINT pk_categories_unique UNIQUE (name),
    CONSTRAINT pk_categories_primary_key PRIMARY KEY (id)
);